import fs from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const fallback = join(root, "demo/fallback");
const esc = (value) => String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const read = (name) => fs.readFile(join(fallback, name), "utf8");
const [plan, implementation, diff, review, finalJson, firstJson, manifestJson] = await Promise.all([read("01-plan.md"),read("02-implementation.md"),read("change.diff"),read("04-review.md"),read("03-verification.json"),read("03-first-verification.json"),read("manifest.json")]);
const final = JSON.parse(finalJson), first = JSON.parse(firstJson), manifest = JSON.parse(manifestJson);
if (!final.success) throw new Error("Evidence viewer requires a successful final verification.");
const checks = final.checks.filter(check=>check.tests>0);
const firstAcceptance = first.checks.find(check=>check.command.some(part=>part.endsWith("refund-acceptance.test.mjs")));
const planStart = plan.indexOf("1. 변경 목표");
const planExcerpt = plan.slice(Math.max(0,planStart), Math.max(0,planStart)+1000);
const diffLines = diff.split("\n");
const ruleLine = diffLines.findIndex(line=>line.includes("refund.amount >= threshold"));
if (ruleLine < 0) throw new Error("Could not locate the actual threshold rule in recorded diff.");
const ruleExcerpt = diffLines.slice(Math.max(0,ruleLine-2), ruleLine+22).join("\n");
const reviewStart = review.indexOf("3. 지적 사항");
const reviewExcerpt = review.slice(Math.max(0,reviewStart),Math.max(0,reviewStart)+1500);
const pages = [
  { id:"plan", title:"정책 요청을 개발 계획으로", lead:"실제 계획 역할의 응답", aside:`<h2>READ ONLY</h2><p>읽기와 검색만 허용</p><hr><p>입력</p><strong>업무 정책 · 현재 코드</strong><p>전달 결과</p><strong>범위 · 완료 기준 · 위험</strong><hr><small>다음 단계에는 명시적 범위 수락이 필요합니다.</small>`, content:`<div class="filename">demo/fallback/01-plan.md · 원문 발췌</div><pre>${esc(planExcerpt)}</pre>` },
  { id:"implementation", title:"화면과 서버를 함께 변경", lead:"실제 구현 역할의 결과와 diff", aside:`<h2>${final.changedFiles.length}개 파일</h2><ul>${final.changedFiles.map(file=>`<li>${esc(file)}</li>`).join("")}</ul><hr><small>외부 패키지·결제·인증·배포는 제외했습니다.</small>`, content:`<div class="filename">change.diff · 서버 정책 부분 원문 발췌</div><pre class="code">${esc(ruleExcerpt)}</pre><div class="note">구현 응답 원문과 전체 diff는 fallback 폴더에 보존했습니다.</div>` },
  { id:"tests", title:"실패를 확인하고 다시 검증", lead:"성공만 편집해서 보여주지 않는 실행 기록", aside:`<h2>${firstAcceptance.passed} / ${firstAcceptance.tests}</h2><p>첫 독립 인수 검증</p><strong>감사 reason 누락 발견</strong><hr><p>후속 검사</p><strong>빈 값도 허용하지 않도록 보완</strong><hr><small>검토에서 발견한 입력 변조 감사 누락도 테스트를 보강해 수정했습니다.</small>`, content:`<div class="filename">demo/fallback/03-verification.json · 최종 기록</div><div class="test-results">${checks.map((check,i)=>`<div><span>${i===0?"제품 테스트":"독립 인수 테스트"}</span><strong>${check.passed} / ${check.tests}</strong><small>exitCode ${check.exitCode}</small></div>`).join("")}</div><div class="command">git diff --check <b>exitCode 0</b></div><div class="note">로컬 테스트 기록입니다. 운영 안전성, GitHub Actions 성공, 출시 승인을 뜻하지 않습니다.</div>` },
  { id:"review", title:"최종 판단은 사람에게", lead:"실제 읽기 전용 검토 역할의 의견", aside:`<h2 class="hold">HOLD</h2><p>운영 출시 보류</p><hr><strong>사람의 검토 대상</strong><p>실제 신원과 권한<br>결제 연동의 경계<br>영구 감사 저장소</p><hr><small>모의 리허설 수락은 실제 사람의 승인이 아닙니다.</small>`, content:`<div class="filename">demo/fallback/04-review.md · 원문 발췌</div><pre>${esc(reviewExcerpt)}</pre>` },
];
const html = `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Copilot 실행 기록 보기</title><style>*{box-sizing:border-box}body{margin:0;background:#101523;color:#edf0f7;font-family:'Nanum Gothic',system-ui,sans-serif}.page{width:1440px;height:900px;padding:96px 60px 58px;position:relative;overflow:hidden}.page[hidden]{display:none}.kicker{font-size:15px;color:#b59ae9;letter-spacing:.12em}h1{font-size:42px;margin:18px 0 12px;letter-spacing:-.045em}.lead{font-size:19px;color:#9ba8bf;margin:0}.columns{display:grid;grid-template-columns:340px 1fr;gap:42px;margin-top:34px;height:543px}aside{padding:24px 0}aside h2{font-size:44px;color:#c8aff8;margin:0 0 18px}aside p{font-size:19px;line-height:1.8;color:#aab7cb}aside strong{font-size:20px;line-height:1.7}aside small{font-size:15px;line-height:1.8;color:#aab7cb}hr{border:0;border-top:1px solid #313b50;margin:22px 0}ul{padding:0;list-style:none;font-family:ui-monospace,monospace;font-size:16px;line-height:2.3;color:#c6d0e0}.panel{background:#f7f8fc;color:#1c2638;border-radius:10px;overflow:hidden;position:relative}.filename{padding:17px 26px;background:#e8e4f1;font:15px ui-monospace,monospace;color:#685584}pre{margin:0;padding:25px 30px;font:18px/1.6 'Nanum Gothic',system-ui,sans-serif;white-space:pre-wrap;overflow:hidden;max-height:476px}.code{font:17px/1.35 ui-monospace,monospace;max-height:429px}.note{margin:22px 28px;font-size:17px;line-height:1.8;color:#69748a}.test-results{display:flex;padding:40px 32px;gap:50px}.test-results span{display:block;color:#7a8397;font-size:18px}.test-results strong{display:block;font-size:64px;color:#267951;margin:18px 0}.test-results small{font-size:17px;color:#357959}.command{margin:15px 30px 0;padding:23px 15px;background:white;font:20px ui-monospace,monospace}.command b{float:right;color:#267951}.hold{color:#e2c58a}footer{position:absolute;bottom:35px;left:61px;right:61px;font-size:13px;color:#8292ab;display:flex;justify-content:space-between}</style>${pages.map((page,index)=>`<section class="page" id="${page.id}" ${index?"hidden":""}><div class="kicker">GITHUB COPILOT CLI / 사전 리허설 실행 기록</div><h1>${page.title}</h1><p class="lead">${page.lead}</p><div class="columns"><aside>${page.aside}</aside><div class="panel">${page.content}</div></div><footer><span>기록을 읽기 쉽게 표시한 화면 · Copilot 제품 UI가 아님</span><span>${esc(manifest.copilot)} · ${esc(manifest.approvalKind)}</span></footer></section>`).join("")}<script>function show(){const id=location.hash.slice(1)||'plan';document.querySelectorAll('.page').forEach(page=>page.hidden=page.id!==id)}addEventListener('hashchange',show);show();</script></html>`;
await fs.mkdir(join(root,".build/video"),{recursive:true});
await fs.writeFile(join(root,".build/video/evidence.html"),html);
await fs.writeFile(join(root,".build/video/evidence-sources.json"),JSON.stringify({manifest:manifest.recordedAt,planSource:"01-plan.md",implementationSource:"change.diff",testsSource:"03-verification.json",reviewSource:"04-review.md",implementationResponse:implementation},null,2));
console.log("Built a read-only viewer of actual recorded evidence, explicitly not product UI.");
